#!/bin/bash
echo "addsubstract mul division"
echo "enter first num A"
read a
echo "enter second num B"
read b
sum=$(($a + $b))
echo "sum of a+b =$sum"
sub=$(($a - $b))
echo "substract a-b = $sub"
mul=$(($a * $b))
echo "multiplication  a*b = $mul"
div==$(($a / $b))
echo "division a/b = $div"

